name: Argos

on:
  push:
    # Argos has to run on your reference branch to creates reference builds
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  argos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: npm ci

      - name: run test
        run: npm run test

      - name: Upload screenshots to argos-ci.com
        continue-on-error: true
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
        run: npm exec argos upload upload ./screenshots
